language : java
jdk :
   - openjdk8
deploy :
   provider : heroku
   api_key :
     secure:  lD77FwwZXbnrIK5PoOVs2kZHQfzonqHr3hsEHDQ2BcXJNc5v74duNzgeYZBH9Iu9OCjCN4qDBlQisdWLlGyU92DVHmf7c1DUoki4I3dyd/+m6rMptWSE2XtdlIJCrfUtUNbd3R4f70idN8D3plfkV0kwf6xKF1nHHnvpwX6SAHMA5XCQMTpqnGuXU9hWwwQ2j/DGpAazAzzoScxpMFDVufyQlAObrAmeds8WDJ8vv3Df/g2F87e54+KwUpFGyqHQugPi8FjwVGXZ95QhMAUhWPAs4kr9jSSKSk+rteYy+tT62l+GaC46JGVu+JJCd3TsDXB5QMGFqLkh6osqq6WMA9PeWf5tvMp9juHPqmzm5wQ5XaITFBMSPTcq3PR10X21mTC42xW0HF2rClNPKziNeMWVISCbFQpsF+0OS0C4fxGhUkc7nQF3opNMLtUjXUlK9HpPtsgDwOJO1eTvjFkxY4jrijsrio7EZERsKVn4GjsGSt9NUHXC9zo7bjNMoCVs5j1JqvnsQ8VUEHyMWZrYELsL9o/qhaPwxBuQdWI/AXNEh6QIo+10Km8wvaniz6c7mGxTzkJb9abIY+QEkKmWNVYm8wCgeYMjT7Ue32X5YDKiUKrI7EkhOLBPDP9N3Ea+B2XmL5/5m7BDxyxtjmeZClaMCTe0MPMSBG6HDJ6+1Wo=
app : grade-curricular-dev123
on :
 all_branches : true